#!/bin/bash
#SBATCH --job-name=SRA_get_fastqs
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -c 4
#SBATCH --partition=general
#SBATCH --qos=general
#SBATCH --mail-type=BEGIN,END
#SBATCH --mail-user=awilderman@uchc.edu
#SBATCH -o SRA_get_fastqs_%j.out
#SBATCH -e SRA_get_fastqs_%j.err

source ~/.bashrc
module load sratoolkit/2.8.2
cd /isg/shared/apps/sratoolkit/2.8.2/bin/

# H9 HiC with reps
# Series GSE105028: "Architectural proteins and pluripotency factors cooperate to orchestrate the transcriptional response of hESCs to temperature stress"
# Lyu X, Rowley MJ, Corces VG. Architectural Proteins and Pluripotency Factors Cooperate to Orchestrate the Transcriptional Response of hESCs to Temperature Stress. Mol Cell 2018 Sep 20;71(6):940-955.e7. PMID: 30122536
# HindIII digest, in-situ

# SRR6177926
# SRR6177927	

prefetch -v SRR6177926
prefetch -v SRR6177927

fastq-dump --outdir ~/DATA/HiC/Human/H9/Lyu --gzip --split-files ~/ncbi/public/sra/SRR6177926.sra
fastq-dump --outdir ~/DATA/HiC/Human/H9/Lyu --gzip --split-files ~/ncbi/public/sra/SRR6177927.sra
